# Site wide configuration

title:            Quickinsights
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Mike Trienis
  avatar: bio-photo-mike.png
  bio: "All about data product and services that scale; from design to implementation"
  email: mike.trienis@quickinsights.io
  twitter: trienism
  google:
    analytics: UA-68277931-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: trienism
  stackoverflow: 3747110/trienism
  linkedin: miketrienis


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
